import { Login_Page } from "../Features_and_Functions/Login_Page/GUI/Login_page.slint";
import { Student_Profile } from "../Features_and_Functions/Profile_Pages/Student_Profile/GUI/Student_Profile.slint";
import { Admin_Profile } from "../Features_and_Functions/Profile_Pages/Admin_Profile/GUI/Admin_Profile.slint";
import { Teacher_Profile } from "../Features_and_Functions/Profile_Pages/Teacher_Profile/GUI/Teacher_Profile.slint";

import { StudentAttendanceData, CourseInfo, StudentGradeData } from "Course_Management/Attendance/Shared/GUI/Shared_Structs.slint";

export component Main_App inherits Window {
    // 0: Login, 1: Student Dashboard, 2: Teacher, 3: Admin
    in-out property <int> active_panel: 0;
    in-out property <bool> login_error_state: false;
    in-out property <string> login_error_msg: "";

    in-out property <string> user_name;
    in-out property <string> user_id;
    in-out property <string> user_Faculty;
    in-out property <string> student_gpa;
    in-out property <string> user_email;
    in-out property <image> user_profile_pic;
    in-out property <string> admin_position;

    // --- STUDENT & TEACHER DATA FORWARDING ---
    in-out property <[CourseInfo]> available_courses;
    in-out property <[CourseInfo]> requested_courses;
    in-out property <[StudentAttendanceData]> students_data;
    callback load_students(string, int);
    callback save_attendance([StudentAttendanceData], string, int);
    in-out property <[CourseInfo]> my_courses;
    in-out property <[string]> teacher_profile_display_list;
    in-out property <[StudentGradeData]> grades_data;
    callback load_grades(string);
    callback save_grades([StudentGradeData], string);
    in-out property <string> status_message;
    in-out property <bool> request_submitted: false;
    callback request_course(string);
    callback submit_course_requests();

    //...................Start Accept and refuse courses admin properties
    in-out property <string> student_id;
    in-out property <string> student_name;
    in-out property <string> faculty;
    in-out property <bool> course1_accept_button_pressed: false;
    in-out property <bool> course2_accept_button_pressed: false;
    in-out property <bool> course3_accept_button_pressed: false;
    in-out property <bool> course4_accept_button_pressed: false;
    in-out property <bool> course5_accept_button_pressed: false;
    in-out property <bool> course1_decline_button_pressed: false;
    in-out property <bool> course2_decline_button_pressed: false;
    in-out property <bool> course3_decline_button_pressed: false;
    in-out property <bool> course4_decline_button_pressed: false;
    in-out property <bool> course5_decline_button_pressed: false;
    in-out property <string> c1_code; in-out property <string> c1_name; in-out property <string> c1_l_day; in-out property <string> c1_l_slot; in-out property <string> c1_t_day;
    in-out property <string> c1_t_slot;
    in-out property <string> c2_code; in-out property <string> c2_name; in-out property <string> c2_l_day; in-out property <string> c2_l_slot;
    in-out property <string> c2_t_day; in-out property <string> c2_t_slot;
    in-out property <string> c3_code; in-out property <string> c3_name; in-out property <string> c3_l_day;
    in-out property <string> c3_l_slot; in-out property <string> c3_t_day; in-out property <string> c3_t_slot;
    in-out property <string> c4_code; in-out property <string> c4_name;
    in-out property <string> c4_l_day; in-out property <string> c4_l_slot; in-out property <string> c4_t_day; in-out property <string> c4_t_slot;
    in-out property <string> c5_code;
    in-out property <string> c5_name; in-out property <string> c5_l_day; in-out property <string> c5_l_slot; in-out property <string> c5_t_day; in-out property <string> c5_t_slot;
    in-out property <bool> Submit_Button_Pressed: false;
    in-out property <bool> show_warning: false;
    in-out property <bool> no_course_requests;
    in-out property <bool> is_next_student_available;
    in-out property <bool> is_previous_student_available;
    //...................end of Accept and refuse courses admin properties

    // Global scale calculation
    out property <float> global_scale: min(self.width / 1024px, self.height / 768px);
    callback check_credentials(string, string, int);
    callback change_picture();
    callback logout();
    callback admin_next_student();
    callback admin_previous_student();
    callback admin_submit_decisions();

    min-height: 600px;
    min-width: 1024px;
    preferred-height: 768px;
    preferred-width: 1024px;
    max-height: 840px;
    max-width: 1300px;
    title: "EUI - SIS";
    background: #f0f0f0;

    // --- Container for all panels ---
    Rectangle {
        width: 100%;
        height: 100%;

        if (active_panel == 0) : Login_Page {
            ui-scale: root.global_scale;
            Error_State <=> root.login_error_state;
            Error_Message <=> root.login_error_msg;

            login_attempted(id, pass, role) => {
                root.check_credentials(id, pass, role);
            }
        }

        if (active_panel == 1) : Student_Profile {
            width: 100%;
            height: 100%;
            ui-scale: root.global_scale;
            Logout => { root.active_panel = 0; }
            user_name: root.user_name;
            user_id: root.user_id;
            user_email: root.user_email;
            user_Faculty: root.user_Faculty;
            user_profile_pic: root.user_profile_pic;
            student_gpa: root.student_gpa;
            change_picture => {root.change_picture(); }

            // Link Student Courses Property
            my_courses <=> root.my_courses;
            available_courses <=> root.available_courses;
            requested_courses <=> root.requested_courses;
            status_message : root.status_message;
            request_submitted <=> root.request_submitted;
            request_course(code) => { root.request_course(code); }
            submit_course_requests() => { root.submit_course_requests(); }
        }

        if (active_panel == 2) : Teacher_Profile {
                    width: 100%;
                    height: 100%;
                    ui-scale: root.global_scale;
                    Logout => { root.active_panel = 0; }

                    // --- LINK THE NEW USER DATA HERE ---
                    user_name <=> root.user_name;
                    user_email <=> root.user_email;
                    user_profile_pic : root.user_profile_pic;
                    change_picture => { root.change_picture(); }
                    // -----------------------------------
                    teacher_display_list <=> root.teacher_profile_display_list;
                    available_courses : root.available_courses;

                    // Link Teacher Properties & Callbacks
                    students_data <=> root.students_data;
                    load_students(course, week) => { root.load_students(course, week); }
                    save_attendance(data, course, week) => { root.save_attendance(data, course, week); }

                    grades_data <=> root.grades_data;
                    load_grades(course) => { root.load_grades(course); }
                    save_grades(data, course) => { root.save_grades(data, course); }
                }

        if (active_panel == 3) : Admin_Profile {
            width: 100%;
            height: 100%;
            ui-scale: root.global_scale;
            Logout => { root.active_panel = 0; }
            change_picture => {root.change_picture()}
            User_profile_pic <=> root.user_profile_pic;
            User_email <=> root.user_email;
            User_name <=> root.user_name;
            admin_position <=> root.admin_position;
            student_id <=> root.student_id;
            student_name <=> root.student_name;
            faculty <=> root.faculty;
            Submit_Button_Pressed <=> root.Submit_Button_Pressed;
            show_warning <=> root.show_warning;
            no_course_requests <=> root.no_course_requests;
            is_next_student_available <=> root.is_next_student_available;
            is_previous_student_available <=> root.is_previous_student_available;

            course1_accept_button_pressed <=> root.course1_accept_button_pressed;
            course2_accept_button_pressed <=> root.course2_accept_button_pressed;
            course3_accept_button_pressed <=> root.course3_accept_button_pressed;
            course4_accept_button_pressed <=> root.course4_accept_button_pressed;
            course5_accept_button_pressed <=> root.course5_accept_button_pressed;

            course1_decline_button_pressed <=> root.course1_decline_button_pressed;
            course2_decline_button_pressed <=> root.course2_decline_button_pressed;
            course3_decline_button_pressed <=> root.course3_decline_button_pressed;
            course4_decline_button_pressed <=> root.course4_decline_button_pressed;
            course5_decline_button_pressed <=> root.course5_decline_button_pressed;

            c1_code <=> root.c1_code; c1_name <=> root.c1_name; c1_l_day <=> root.c1_l_day; c1_l_slot <=> root.c1_l_slot;
            c1_t_day <=> root.c1_t_day; c1_t_slot <=> root.c1_t_slot;
            c2_code <=> root.c2_code; c2_name <=> root.c2_name; c2_l_day <=> root.c2_l_day; c2_l_slot <=> root.c2_l_slot;
            c2_t_day <=> root.c2_t_day; c2_t_slot <=> root.c2_t_slot;
            c3_code <=> root.c3_code; c3_name <=> root.c3_name; c3_l_day <=> root.c3_l_day; c3_l_slot <=> root.c3_l_slot;
            c3_t_day <=> root.c3_t_day; c3_t_slot <=> root.c3_t_slot;
            c4_code <=> root.c4_code; c4_name <=> root.c4_name; c4_l_day <=> root.c4_l_day; c4_l_slot <=> root.c4_l_slot;
            c4_t_day <=> root.c4_t_day; c4_t_slot <=> root.c4_t_slot;
            c5_code <=> root.c5_code; c5_name <=> root.c5_name; c5_l_day <=> root.c5_l_day; c5_l_slot <=> root.c5_l_slot;
            c5_t_day <=> root.c5_t_day; c5_t_slot <=> root.c5_t_slot;

            // Tie the buttons clicks to the root callbacks
            admin_next_student => { root.admin_next_student(); }
            admin_previous_student => { root.admin_previous_student(); }
            admin_submit_decisions => { root.admin_submit_decisions(); }
        }
    }
}