import { Login_Page } from "../Features_and_Functions/Login_Page/GUI/Login_page.slint";
import { Student_Profile } from "../Features_and_Functions/Profile_Pages/Student_Profile/GUI/Student_Profile.slint";
import { Admin_Profile } from "../Features_and_Functions/Profile_Pages/Admin_Profile/GUI/Admin_Profile.slint";
import { Teacher_Profile } from "../Features_and_Functions/Profile_Pages/Teacher_Profile/GUI/Teacher_Profile.slint";
export component Main_App inherits Window {
    // 0: Login, 1: Student Dashboard, 2: Teacher, 3: Admin
    in-out property <int> active_panel: 0;
    in-out property <bool> login_error_state: false;
    in-out property <string> login_error_msg: "";

    // Global scale calculation
    out property <float> global_scale: min(self.width / 1024px, self.height / 768px);

    callback check_credentials(string, string, int);

    min-height: 600px;
    min-width: 1024px;
    preferred-height: 768px;
    preferred-width: 1024px;
    max-height: 840px;
    max-width: 1300px;
    title: "EUI - SIS";
    background: #f0f0f0;

    // --- Container for all panels ---
    Rectangle {
        width: 100%;
        height: 100%;

        if (active_panel == 0) : Login_Page {
            // Ensure these property names match exactly what is in Login_page.slint
            ui-scale: root.global_scale;
            Error_State <=> root.login_error_state;
            Error_Message <=> root.login_error_msg;

            login_attempted(id, pass, role) => {
                root.check_credentials(id, pass, role);
            }
        }

        if (active_panel == 1) : Student_Profile {
            width: 100%;
            height: 100%;
            ui-scale: root.global_scale;
            Logout => { root.active_panel = 0; }
        }
            if (active_panel == 2) : Teacher_Profile {
                width: 100%;
                height: 100%;
                ui-scale: root.global_scale;
                Logout => { root.active_panel = 0; }
            }

        if (active_panel == 3) : Admin_Profile {
            width: 100%;
            height: 100%;
            ui-scale: root.global_scale;
            Logout => { root.active_panel = 0; }
        }
    }
}