export struct StudentAttendanceData {
    id: string,
    name: string,
    present: bool,
}

export struct CourseInfo {
    course_code: string,
    course_name: string,
    instructor_name: string,
    credit_hours: string,
    lecture_slot: string,
    tutorial_slot: string,
    attendance_summary: string, // e.g., "Present: 4/5"
    grade_summary: string,
    detailed_grades: string,
    is_eligible: bool,
    is_requested: bool,
    is_failed: bool,
    has_final_grade: bool,
}
export struct StudentGradeData {
    id: string,
    quiz1: string,
    quiz2: string,
    ass1: string,
    ass2: string,
    midterm: string,
    project: string,
    final_mark: string,
    total: string,
    letter: string,
    gpa: string,
}