import { ScrollView } from "std-widgets.slint";
import { CourseInfo } from "../../../Attendance/Shared/GUI/Shared_Structs.slint";

export component Previous_Enrollments inherits Rectangle {
    in property <[CourseInfo]> passed_courses;
    in property <[CourseInfo]> failed_courses;
    in property <string> student_name;
    in property <string> student_id;
    in property <string> student_gpa;
    in property <float> ui-scale: 1.0;

    HorizontalLayout {
        spacing: 20px * root.ui-scale;
        padding: 20px * root.ui-scale;

        VerticalLayout {
            spacing: 10px * root.ui-scale;
            Text { text: "Passed Courses"; color: black; font-weight: 700; font-size: 16px * root.ui-scale; horizontal-alignment: center; }
            ScrollView {
                VerticalLayout {
                    spacing: 5px * root.ui-scale;
                    for course in root.passed_courses: Rectangle {
                        height: 40px * root.ui-scale; background: #00ff00 ; border-radius: 4px;
                        Text { text: course.course_code; color: black; horizontal-alignment: center; vertical-alignment: center; }
                    }
                }
            }
        }

        VerticalLayout {
            spacing: 10px * root.ui-scale;
            Text { text: "Failed Courses"; color: black; font-weight: 700; font-size: 16px * root.ui-scale; horizontal-alignment: center; }
            ScrollView {
                VerticalLayout {
                    spacing: 5px * root.ui-scale;
                    for course in root.failed_courses: Rectangle {
                        height: 40px * root.ui-scale; border-color: #F44336; border-radius: 4px;
                        Text { text: course.course_code; color: black; horizontal-alignment: center; vertical-alignment: center; }

                    }
                }
            }
        }
    }
}