import { ScrollView } from "std-widgets.slint";
import { CourseInfo } from "../../../../Course_Management/Attendance/Shared/GUI/Shared_Structs.slint";

export component Previous_Enrollments inherits Rectangle {
    in-out property <float> ui-scale: 1.0;
    in-out property <[CourseInfo]> passed_courses;
    in-out property <[CourseInfo]> failed_courses ;
    in-out property <string> student_name: "";
    in-out property <string> student_id: "";
    in-out property <string> student_gpa: "";
    background: #fdfdfd;

    VerticalLayout {
        padding: 50px * ui-scale;
        spacing: 15px * ui-scale;

       // Display the Student Info at the top
        HorizontalLayout {
        Text { text: "Academic History for: " + root.student_name; font-size: 20px; font-weight: 700; color : #000000; vertical-alignment: center; }
        Rectangle { width: 20px; } // Spacer
        Text { text: "ID: " + root.student_id; color: #000000; vertical-alignment: center; font-weight: 700; font-size: 19px * ui-scale;}
        }
        Text { text: "Cumulative GPA: " + root.student_gpa; color: #1a237e; font-weight: 700;font-size: 18px * ui-scale; }

        Text { text: "Passed Courses"; color: #2e7d32; font-weight: 700; font-size: 18px * ui-scale; }
        Rectangle {
            background: #f1f8e9; border-radius: 8px; height: 150px;

                VerticalLayout {
                    padding: 10px; spacing: 5px;

                    for course in root.passed_courses: Rectangle {
                        height: 60px; // Force a large height to see if they appear
                        background: white;
                        border-width: 2px;
                        border-color: green; // Green border so we can see the box

                        Text {
                            text: "DEBUG: " + course.course_name; // Add DEBUG text
                            color: black;
                        }
                    }
                }

        }

        Text { text: "Failed / Retake Required"; color: #c62828; font-weight: 700; font-size: 18px * ui-scale; }
        Rectangle {
            background: #ffebee; border-radius: 8px; height: 150px;
            ScrollView {
                VerticalLayout {
                    padding: 10px; spacing: 5px;

                        for course in root.failed_courses: Rectangle {
                            height: 60px; // Force a large height to see if they appear
                            background: white;
                            border-width: 2px;
                            border-color: red; // Red border so we can see the box

                            Text {
                                text: "DEBUG: " + course.course_name; // Add DEBUG text
                                color: black;
                            }
                        }
                }
            }
        }
    }
}