import { ComboBox, ScrollView, CheckBox, Button } from "std-widgets.slint";
import { StudentAttendanceData } from "../../Shared/GUI/Shared_Structs.slint";

export component Teacher_Attendance_Panel inherits Rectangle {
    in-out property <float> ui-scale: 1.0;
    in property <[string]> available_courses;
    in property <[string]> available_weeks: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"];
    in property <[StudentAttendanceData]> students_data;

    out property <string> selected_course: available_courses[0];
    out property <int> selected_week: 1;

    callback load_students(string, int);
    callback save_attendance([StudentAttendanceData], string, int);

    init => {
            root.load_students(root.selected_course, root.selected_week);
        }

    background: white;

    VerticalLayout {
        padding: 20px * root.ui-scale;
        spacing: 20px * root.ui-scale;

        Text { text: "Manage Course Attendance"; color:black; font-size: 24px * root.ui-scale; font-weight: 700; }

        HorizontalLayout {
            spacing: 20px * root.ui-scale;
            height: 40px * root.ui-scale;
            ComboBox {
                model: available_courses;
                current-value: root.selected_course;
                selected(val) => {
                    root.selected_course = val;
                    root.load_students(val, root.selected_week);
                }
            }
            ComboBox {
                model: available_weeks;
                current-value: "1";
                selected(val) => {
                    root.selected_week = val.to-float();
                    root.load_students(root.selected_course, root.selected_week);
                }
            }
        }

        ScrollView {
            VerticalLayout {
                spacing: 10px * root.ui-scale;
                for student[i] in students_data: Rectangle {
                    height: 50px * root.ui-scale;
                    background: #f4f6f9; border-radius: 8px * root.ui-scale;
                    HorizontalLayout {
                        padding: 10px * root.ui-scale;
                        spacing: 20px * root.ui-scale;

                        Text {
                            text: student.id;
                            color:black;
                            width: 100px * root.ui-scale;
                            vertical-alignment: center;
                            font-weight: 600;
                        }

                        Text {
                            text: student.name;
                            color:black;
                            width: 200px * root.ui-scale;
                            vertical-alignment: center;
                        }

                        // This empty Rectangle acts as a spring,
                        // pushing everything after it to the far right.
                        Rectangle { }

                        // Optional: Smaller label right next to the box
                        Text {
                            text: "Present:";
                            vertical-alignment: center;
                            color: #666;
                        }

                        CheckBox {
                            checked: student.present;
                            toggled => { student.present = !student.present; }
                        }
                    }
                }
            }
        }

        Submit_Button := Rectangle {
            width: Submit_Button_Touch.has-hover ? 210px * root.ui-scale :200px * root.ui-scale;
            height: Submit_Button_Touch.has-hover ? 65px * root.ui-scale :60px * root.ui-scale;
            x: (parent.width - self.width) / 2;
            background: Submit_Button_Touch.pressed? #00ff44 : #218838;
            border-radius: 15px * root.ui-scale;
            animate width, height, background { duration: 150ms; easing: ease-in; }

            Text { text: "Submit";
                   color: black;
                   font-size: 22px * root.ui-scale;
            }
            Submit_Button_Touch:= TouchArea {
                clicked=>{root.save_attendance(root.students_data,root.selected_course,root.selected_week);}
            }
        }
    }
}