export component Login_Page inherits Rectangle {
    //properties
    property <float> ui-scale: min(root.width / 1024px, root.height / 768px);
    property <bool> Student_pressed: false;
    property <bool> Teacher_pressed: false;
    property <bool> Admin_pressed: false;



    min-height: 600px;
    min-width: 1024px;
    preferred-height: 768px;
    preferred-width: 1024px;
    max-height: 1080px;
    max-width: 1920px;
    background: #d0d2d6;


        Title:=Rectangle{
            width: 200px * root.ui-scale;
            height: 55px * root.ui-scale;
            x: (parent.width - self.width) / 2;
            y: 100px * (root.height / 768px);
            background: #007bff;
            border-radius: 15px * root.ui-scale;
            Text{

                text: "Login Page";
                color: white;
                font-size: 28px * root.ui-scale;

                horizontal-alignment: center;
                vertical-alignment: center;
            }
        }

    Login_Type:=Rectangle{
    width: 1000px * root.ui-scale;
    height: 90px * root.ui-scale;
    x: (parent.width - self.width) / 2;
    y: 200px * (root.height / 768px);
    border-radius: 15px * root.ui-scale;
    background: white;

    Student_Button:=Rectangle{
    width: Student_Touch.has-hover ? 240px * root.ui-scale:230px * root.ui-scale;
    height: Student_Touch.has-hover ? 65px * root.ui-scale :60px * root.ui-scale;
    animate width, height { duration: 100ms;}
    animate background { duration: 100ms; }


    x: 60px * (parent.width / 1024px);
    y: (parent.height - self.height) / 2;
    background: Student_Touch.pressed ? #0056b3 : #007bff;
    border-radius: 15px * root.ui-scale;
        Text{
        text: "Student";
        color: white;
        font-size: 30px * root.ui-scale;

        horizontal-alignment: center;
        vertical-alignment: center;
        }
        Student_Touch:=TouchArea {
            width: 100%;
            height: 100%;
            clicked => {
                Student_pressed = true;
                Teacher_pressed = false;
                Admin_pressed = false;

            }
        }
    }
    Teacher_Button:=Rectangle{
        width: Teacher_Touch.has-hover ? 240px * root.ui-scale:230px * root.ui-scale;
        height: Teacher_Touch.has-hover ? 65px * root.ui-scale :60px * root.ui-scale;
        animate width, height { duration: 100ms;}
        animate background { duration: 100ms; }


        x: 400px * (parent.width / 1024px);
        y: (parent.height - self.height) / 2;
        background: Teacher_Touch.pressed ? #0056b3 : #007bff;
        border-radius: 15px * root.ui-scale;
            Text{
            text: "Teacher";
            color: white;
            font-size: 30px * root.ui-scale;

            horizontal-alignment: center;
            vertical-alignment: center;
            }
            Teacher_Touch:=TouchArea {
                width: 100%;
                height: 100%;
                clicked => {
                Student_pressed = false;
                Teacher_pressed = true;
                Admin_pressed = false;

                }
            }
        }

        Admin_Button:=Rectangle{
                width: Admin_Touch.has-hover ? 240px * root.ui-scale:230px * root.ui-scale;
                height: Admin_Touch.has-hover ? 65px * root.ui-scale :60px * root.ui-scale;
                animate width, height { duration: 100ms;}
                animate background { duration: 100ms; }


                x: 730px * (parent.width / 1024px);
                y: (parent.height - self.height) / 2;
                background: Admin_Touch.pressed ? #0056b3 : #007bff;
                border-radius: 15px * root.ui-scale;
                    Text{
                    text: "Admin";
                    color: white;
                    font-size: 30px * root.ui-scale;

                    horizontal-alignment: center;
                    vertical-alignment: center;
                    }
                    Admin_Touch:=TouchArea {
                        width: 100%;
                        height: 100%;
                        clicked => {
                        Student_pressed = false;
                        Teacher_pressed = false;
                        Admin_pressed = true;

                        }
                    }
                }


    }
    Username_Input:=Rectangle{
        width: 1000px * root.ui-scale;
        height: 360px * root.ui-scale;
        x: (parent.width - self.width) / 2;
        y: 320px * (parent.height / 768px);
        background: white;
        border-radius: 15px * root.ui-scale;
        ID_Email:=Rectangle{
            width: 880px * root.ui-scale;
            height: 80px * root.ui-scale;
            x: 60px * (parent.width / 1024px);
            y: 130px * (parent.height / 768px);
            background: #d0d2d6;
            border-radius: 15px * root.ui-scale;
        Username:=Text{
            text: Student_pressed ? "ID:" :
                  Teacher_pressed ? "Email:" :
                  Admin_pressed ? "Email:" : "ID:";
            color: black;
            font-size: 30px * root.ui-scale;
            x: 60px * (parent.width / 1024px);
            y: (parent.height - self.height) / 2;
            }
        }
        Password:=Rectangle{
                    width: 880px * root.ui-scale;
                    height: 80px * root.ui-scale;
                    x: 60px * (parent.width / 1024px);
                    y: 430px * (parent.height / 768px);
                    background: #d0d2d6;
                    border-radius: 15px * root.ui-scale;
                Password_text:=Text{
                    text: "Password:";
                    color: black;
                    font-size: 30px * root.ui-scale;
                    x: 60px * (parent.width / 1024px);
                    y: (parent.height - self.height) / 2;
                    }
                }
    }



}

